on:
  push:

jobs:
  specs:
    runs-on: ubuntu-latest
    needs: diffend
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install latest bundler
        run: gem install bundler --no-document
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run all tests
        run: bundle exec rspec

  diffend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install latest bundler
        run: gem install bundler --no-document
      - name: Install Diffend plugin
        run: bundle plugin install diffend
      - name: Bundle Secure
        run: bundle secure
